도커 이미지 빌드 및 동작 가능한 상태로 Dockerfile 수정
kakao/khaiii pull request #98
Opened 2020-12-20 17:53 UTC by tooget

설명 (Description)
----
도커 이미지 빌드 및 실행이 되지 않아 수정합니다.

 - 빌드 에러, Docker version 19.03.13, build 4484c46d9d / macOS 10.13.6
```
SUNGHYUNs-MacBook-Air:khaiii hyun$ docker build -t khaiii_buildtest docker
[+] Building 526.4s (5/18)                                                                                                                                                                                                                    
 => [internal] load .dockerignore                                                                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                     0.1s
 => => transferring dockerfile: 493B                                                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/pytorch/pytorch:latest                                                                                                                                                                        3.2s
 => [1/15] FROM docker.io/pytorch/pytorch:latest@sha256:9cffbe6c391a0dbfa2a305be24b9707f87595e832b444c2bde52f0ea183192f1                                                                                                               520.8s
 => => resolve docker.io/pytorch/pytorch:latest@sha256:9cffbe6c391a0dbfa2a305be24b9707f87595e832b444c2bde52f0ea183192f1                                                                                                                  0.0s
 => => sha256:171857c49d0f5e2ebf623e6cb36a8bcad585ed0c2aa99c87a055df034c1e5848 26.70MB / 26.70MB                                                                                                                                         8.6s
 => => sha256:419640447d267f068d2f84a093cb13a56ce77e130877f5b8bdb4294f4a90a84f 852B / 852B                                                                                                                                               0.2s
 => => sha256:61e52f862619ab016d3bcfbd78e5c7aaaa1989b4c295e6dbcacddd2d7b93e1f5 162B / 162B                                                                                                                                               0.4s
 => => sha256:9cffbe6c391a0dbfa2a305be24b9707f87595e832b444c2bde52f0ea183192f1 1.57kB / 1.57kB                                                                                                                                           0.0s
 => => sha256:f8a1d10ae3d76586848267c59b6439e74998ef87ebf9677489eddd9bb6ecc78f 4.35kB / 4.35kB                                                                                                                                           0.0s
 => => sha256:32ccbf4f7cd53843b06e51187543ba09119069c1c5d2dac3338e9009299f24b6 9.93MB / 9.93MB                                                                                                                                           4.5s
 => => sha256:829fa419a90a8d223664e8f365d4b60e32bae27fba1f79d4ccf10bc5235605a5 2.32GB / 2.32GB                                                                                                                                         301.2s
 => => sha256:c32f85837aeb4128f8f01ae5b73a8247ad062f3803b00901ae4675117210ad69 138B / 138B                                                                                                                                               4.9s
 => => extracting sha256:171857c49d0f5e2ebf623e6cb36a8bcad585ed0c2aa99c87a055df034c1e5848                                                                                                                                               10.8s
 => => extracting sha256:419640447d267f068d2f84a093cb13a56ce77e130877f5b8bdb4294f4a90a84f                                                                                                                                                0.0s
 => => extracting sha256:61e52f862619ab016d3bcfbd78e5c7aaaa1989b4c295e6dbcacddd2d7b93e1f5                                                                                                                                                0.0s
 => => extracting sha256:32ccbf4f7cd53843b06e51187543ba09119069c1c5d2dac3338e9009299f24b6                                                                                                                                                6.7s
 => => extracting sha256:829fa419a90a8d223664e8f365d4b60e32bae27fba1f79d4ccf10bc5235605a5                                                                                                                                              213.6s
 => => extracting sha256:c32f85837aeb4128f8f01ae5b73a8247ad062f3803b00901ae4675117210ad69                                                                                                                                                0.0s
 => ERROR [2/15] RUN git clone https://github.com/kakao/khaiii.git                                                                                                                                                                       2.3s
------                                                                                                                                                                                                                                        
 > [2/15] RUN git clone https://github.com/kakao/khaiii.git:
#5 2.188 /bin/sh: 1: git: not found
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c git clone https://github.com/kakao/khaiii.git]: runc did not terminate sucessfully
```

 - 수정후 빌드 성공
```
SUNGHYUNs-MacBook-Air:khaiii hyun$ docker build -t khaiii_buildtest docker
[+] Building 820.1s (17/17) FINISHED                                                                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                                                                     0.1s
 => => transferring dockerfile: 468B                                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/pytorch/pytorch:latest                                                                                                                                                                        2.3s
 => CACHED [1/13] FROM docker.io/pytorch/pytorch:latest@sha256:9cffbe6c391a0dbfa2a305be24b9707f87595e832b444c2bde52f0ea183192f1                                                                                                          0.0s
 => [2/13] RUN apt-get update -y   [...]

2020-12-21 02:19 UTC, krikit commented
@tooget 

우선 수정해서 PR 주신데 대해 감사드립니다.

카카오에서는 국내 컨트리뷰터의 경우 개인정보동의가 필요합니다.
이는 국내법에 의한 것이며, 최초의 커밋에 한해 동의해 주시면 됩니다.
이후 커밋 부터는 필요 없는 절차입니다.

위 [cla-bot의 글](https://github.com/kakao/khaiii/pull/98#issuecomment-748639116)을 잘 보시고, 서명 후 메일로 제출을 부탁드립니다.

감사합니다.

2020-12-21 05:03 UTC, tooget commented
> @tooget
> 
> 우선 수정해서 PR 주신데 대해 감사드립니다.
> 
> 카카오에서는 국내 컨트리뷰터의 경우 개인정보동의가 필요합니다.
> 이는 국내법에 의한 것이며, 최초의 커밋에 한해 동의해 주시면 됩니다.
> 이후 커밋 부터는 필요 없는 절차입니다.
> 
> 위 [cla-bot의 글](https://github.com/kakao/khaiii/pull/98#issuecomment-748639116)을 잘 보시고, 서명 후 메일로 제출을 부탁드립니다.
> 
> 감사합니다.

@krikit 
메일 송부 드렸습니다.
안내 감사합니다.

> title: CLA(Kakao)_SUNGHYUN KIM_12-21-2020 12.25
> to: oss@kakaocorp.com
> from: tooget@gmail.com
> * Khaiii가 향후 Apache License 2.0(혹은 MIT 등 불특정 다수가 특별한 제약 없이 사용할 수 있는 라이선스)를 유지하는 것을 전제로 CLA에 동의합니다.

2020-12-22 02:40 UTC, oss-kakao commented
@cla-bot check

2020-12-22 02:46 UTC, oss-kakao commented
@cla-bot check

2020-12-22 04:08 UTC, oss-kakao commented
@cla-bot check

2020-12-22 04:14 UTC, oss-kakao commented
@cla-bot check

2020-12-22 04:27 UTC, krikit requested changes
.clabot 파일은 CLA(contributor license agreement)에 동의한 contributor를 저장하는 파일입니다.
master에만 유지하기로 했는데요. 이 파일을 제거해 주시면 좋겠습니다.

2020-12-22 04:47 UTC, tooget commented
> .clabot 파일은 CLA(contributor license agreement)에 동의한 contributor를 저장하는 파일입니다.
> master에만 유지하기로 했는데요. 이 파일을 제거해 주시면 좋겠습니다.

@krikit 
커멘트 감사드립니다.
파일 삭제하였습니다.

2020-12-22 04:59 UTC, krikit commented
conflict가 나서 확인해 봤더니 도커 파일이 master와 develop의 상태가 달라서였네요.
도커 관련해서 여러 분들께서 도움을 주셨고, 지금은 처음의 도커 파일과 많이 다릅니다.
- 참고: https://github.com/kakao/khaiii/tree/develop/docker

아마 @tooget 님은 master 브랜치를 사용하셨을 거고, 최신 변경은 develop 브랜치에 있습니다.
그래서 이 PR은 머지하기 힘들 것 같습니다.
처음부터 이 부분을 인지하지 못해서 괜히 시간을 허비하게 되어 죄송합니다.

2020-12-22 05:07 UTC, tooget commented
@krikit

- 아나콘다 이미지 베이스에 `build-essential` 을 사용한 파일이 이미 있었네요. PR 닫도록 하겠습니다.
- 조속한 master 머지를 기원합니다.

감사합니다.

2020-12-22 05:07 UTC, closed without merging